seed_base: 2
grad_clip: 5

model:
    type: NACSearchSpace
    kwargs:
        in_dim: 3703
        out_dim: 6
        hidden_size: 32
        num_layers: 3
        dropout: 0.6
        epsilon: 0.0
        with_conv_linear: False
        fix_last: False
        with_bn: False

nas:
    type: nac
    kwargs:
        config:
            momentum: 0.9
            weight_decay: 0.0005
            arch_learning_rate: 0.0003
            arch_weight_decay: 0.001002
            unrolled: False
            subnet:
                subnet_settings:
                    genotype_filename: ../results/searched_result.txt
                    hidden_size: 64
                    in_dropout: 0.5
                    out_dropout: 0.5
                    act: relu
                    config:
                        fix_last: True
                        with_linear: False
                        with_layernorm: False
                optimizer:
                    type: Adam
                    kwargs:
                        lr: 0.005937
                        weight_decay: 0.00002007
                lr_scheduler:
                    type: CosineAnnealingLR
                    kwargs:
                        T_max: 400
                        last_epoch: -1
                data:
                    max_epoch: 400

optimizer:
    type: SGD
    kwargs:
        lr: 0.025
        weight_decay: 0.0005
        # nesterov: True
        # momentum: 0.9

lr_scheduler:
    type: CosineAnnealingLR
    kwargs:
        T_max: 100
        eta_min: 0.001
        last_epoch: -1

data:
    task: CiteSeer
    max_epoch: 100

saver:                                # saving or loading details
    print_freq: 10                    # frequence of printing logger
    val_epoch_freq: 1
    val_freq: 500                    # frequence of evaluating during training
    save_many: False                   # whether to save checkpoints after every evaluation
    # pretrain:
    #    path: ./checkpoints/ckpt.pth.tar